# Generated by Django 5.1.6 on 2025-03-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coupon_review_shippinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
