# Generated by Django 5.1.6 on 2025-03-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_shippinginfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
