# Generated by Django 5.1.6 on 2025-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang xử lý'), ('shipped', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
