# Generated by Django 5.1.6 on 2025-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_checkoutinfo_status_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='status',
            field=models.CharField(choices=[('paid', 'Đã thanh toán'), ('pending', 'Đang xử lý'), ('shipped', 'Đã giao hàng'), ('received', 'Đã nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
