# Generated by Django 5.1.6 on 2025-03-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_checkoutinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='status',
        ),
    ]
